[workspace]
authors = ["Mike Xiangyu Liu <liu.xiangyu@ucy.ac.cy>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "VLAD-BuFF"
platforms = ["linux-64"]
version = "0.1.0"
channel-priority = "disabled"

[activation.env]
NCCL_SOCKET_IFNAME = "^docker0,lo"

[tasks]
test = { cmd = "python -c \"import torch; print('torch:', torch.__version__); print('cuda available:', torch.cuda.is_available()); print(torch.cuda.mem_get_info())\"" }

[tasks.train-xfeat]
cmd = '''
python train.py
  --aggregation NETVLAD 
  --backbone xfeat 
  --expName xfeat_conv_upsample_NV_AB
  --antiburst 
  --no_wandb 
  --pl_seed False
  --batch_size 16
  --num_workers 12
  --reduce_feature_dims False
  --reduce_token_dims False
  --epochs 100
'''

[dependencies]
python = "3.10.*"
pip = "*"
numpy = "<2"
pillow = "*"   # ← this will install the conda-forge version, not a wheel

[pypi-dependencies]
bitsandbytes = "==0.41.1"
pandas = "*"
prettytable = "==3.9.0"
pytorch-lightning = "==2.5.1"
pytorch-metric-learning = "*"
lightning-fabric = "==2.5.1"
torchmetrics = "==1.2.0"
wandb = "*"
opencv-python = "*"
natsort = "*"
matplotlib = "*"
scikit-image = "*"
seaborn = "*"
mpld3 = "*"
lightning = { version = "*", extras = ["extra"] }
triton = "*"
faiss-gpu = "*"
torch       = { version = "==2.5.1", index = "https://download.pytorch.org/whl/cu121" }
torchvision = { version = "==0.20.1", index = "https://download.pytorch.org/whl/cu121" }
torchaudio  = { version = "==2.5.1", index = "https://download.pytorch.org/whl/cu121" }

[system-requirements]
cuda = "12"
